# Generated by Django 4.2.4 on 2024-11-01 04:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('prise', '0003_priseplanning'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriseRelaiState',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=False)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('couleur', models.CharField(blank=True, max_length=100, null=True)),
                ('valeur', models.CharField(blank=True, max_length=100, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('prise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prise_relai_state', to='prise.prise')),
            ],
        ),
    ]
