# Generated by Django 4.2.4 on 2024-11-01 04:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('prise', '0004_priserelaistate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriseReference',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('checked_data', models.BooleanField(default=False)),
                ('checked_state', models.BooleanField(default=False)),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('consommation', models.CharField(blank=True, max_length=100, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('prise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prise_reference', to='prise.prise')),
            ],
        ),
    ]
