# Generated by Django 4.2.4 on 2024-11-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prise', '0005_prisereference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priserelaistate',
            name='couleur',
            field=models.CharField(blank=True, default='red', max_length=100),
        ),
        migrations.AlterField(
            model_name='priserelaistate',
            name='state',
            field=models.CharField(blank=True, default='low', max_length=100),
        ),
        migrations.AlterField(
            model_name='priserelaistate',
            name='valeur',
            field=models.CharField(blank=True, default=0, max_length=100),
        ),
    ]
