# Generated by Django 4.2.4 on 2025-08-19 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prise', '0006_alter_priserelaistate_couleur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='priseplanning',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prisereference',
            name='prise',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prise_reference', to='prise.prise'),
        ),
    ]
