# Generated by Django 4.2.4 on 2024-11-30 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prise', '0006_alter_priserelaistate_couleur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='priseplanning',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='priseplanning',
            name='date_debut',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='priseplanning',
            name='date_fin',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
