# Generated by Django 4.2.4 on 2024-11-30 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prise', '0007_priseplanning_date_alter_priseplanning_date_debut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prisereference',
            name='prise',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prise_reference', to='prise.prise'),
        ),
    ]
