# Generated by Django 4.2.4 on 2025-10-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prise', '0007_priseplanning_date_alter_prisereference_prise'),
    ]

    operations = [
        migrations.AddField(
            model_name='prisedata',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
