# Generated by Django 4.2.4 on 2025-10-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prise', '0008_prisedata_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prisedata',
            name='is_active',
        ),
        migrations.AddField(
            model_name='prise',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
