# Generated by Django 4.2.4 on 2025-12-05 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prise', '0009_remove_prisedata_is_active_prise_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priserelaistate',
            name='prise',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prise_relai_state', to='prise.prise'),
        ),
    ]
