# Generated by Django 4.2.4 on 2024-11-24 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usertoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiluser',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
