# Generated by Django 4.2.4 on 2024-11-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profiluser_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiluser',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
