# Generated by Django 4.2.4 on 2025-08-20 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profiluser_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiluser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
