# Generated by Django 4.2.4 on 2024-11-05 05:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('stockage_ensuel', models.CharField(blank=True, max_length=200, null=True)),
                ('assistance', models.CharField(blank=True, max_length=200, null=True)),
                ('entretien', models.CharField(blank=True, max_length=200, null=True)),
                ('monitoring', models.CharField(blank=True, max_length=200, null=True)),
                ('remote_control', models.CharField(blank=True, max_length=200, null=True)),
                ('planing', models.CharField(blank=True, max_length=200, null=True)),
                ('alert', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
