# Generated by Django 4.2.4 on 2024-11-01 03:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('module', '0003_modulesdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Panneau',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('marque', models.CharField(blank=True, max_length=200, null=True)),
                ('puissance', models.CharField(blank=True, max_length=200, null=True)),
                ('voltage', models.CharField(blank=True, max_length=200, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules_panneau', to='module.modules')),
            ],
        ),
    ]
