# Generated by Django 4.2.4 on 2024-11-01 03:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('panneau', '0002_panneaudata'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanneauPlanning',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('energie', models.CharField(blank=True, max_length=100, null=True)),
                ('date_debut', models.DateTimeField(blank=True, null=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('done', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('panneau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panneau_planning', to='panneau.panneau')),
            ],
        ),
    ]
