# Generated by Django 4.2.4 on 2024-11-01 03:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('panneau', '0003_panneauplanning'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanneauRelaiState',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=False)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('couleur', models.CharField(blank=True, max_length=100, null=True)),
                ('valeur', models.CharField(blank=True, max_length=100, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('panneau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panneau_relai_state', to='panneau.panneau')),
            ],
        ),
    ]
