# Generated by Django 4.2.4 on 2024-11-01 03:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('panneau', '0004_panneaurelaistate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanneauReference',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('checked_data', models.BooleanField(default=False)),
                ('checked_state', models.BooleanField(default=False)),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('energy', models.CharField(blank=True, max_length=100, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('panneau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panneau_reference', to='panneau.panneau')),
            ],
        ),
    ]
