# Generated by Django 4.2.4 on 2024-11-30 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panneau', '0006_alter_panneaurelaistate_couleur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panneaureference',
            name='panneau',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='panneau_reference', to='panneau.panneau'),
        ),
    ]
