# Generated by Django 4.2.4 on 2025-10-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panneau', '0007_alter_panneaureference_panneau'),
    ]

    operations = [
        migrations.AddField(
            model_name='panneau',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
