# Generated by Django 4.2.4 on 2025-12-05 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panneau', '0008_panneau_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panneaurelaistate',
            name='panneau',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='panneau_relai_state', to='panneau.panneau'),
        ),
    ]
