# Generated by Django 4.2.4 on 2024-10-29 09:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0002_modulesinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModulesDetail',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('module_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_detail', to='module.modulesinfo')),
            ],
        ),
    ]
