# Generated by Django 4.2.4 on 2024-11-05 08:22

from django.db import migrations, models
import module.models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0003_modulesdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modules',
            name='gr_code',
            field=models.ImageField(blank=True, default='grcode.jpg', null=True, upload_to=module.models.upload_to),
        ),
    ]
