# Generated by Django 4.2.4 on 2024-11-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0004_alter_modules_gr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
