# Generated by Django 4.2.4 on 2024-11-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0005_modules_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modules',
            name='identifiant',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='modules',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='modules',
            name='password',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
