# Generated by Django 4.2.4 on 2025-01-08 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0006_alter_modules_identifiant_alter_modules_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modules',
            name='name',
        ),
    ]
