# Generated by Django 4.2.4 on 2025-01-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0007_remove_modules_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modules',
            name='gr_code',
        ),
        migrations.AddField(
            model_name='modules',
            name='reference',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
