# Generated by Django 4.2.4 on 2025-07-31 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0008_remove_modules_gr_code_modules_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modules',
            name='activation_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
