# Generated by Django 4.2.4 on 2025-11-11 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0009_modules_activated_at_modules_activation_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modules',
            old_name='identifiant',
            new_name='reference_battery',
        ),
        migrations.RenameField(
            model_name='modules',
            old_name='password',
            new_name='reference_panneau',
        ),
        migrations.RenameField(
            model_name='modules',
            old_name='reference',
            new_name='reference_prise',
        ),
    ]
