# Generated by Django 4.2.4 on 2024-11-01 02:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('battery', '0003_batteryplanning'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatteryRelaiState',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=False)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('couleur', models.CharField(blank=True, max_length=100, null=True)),
                ('valeur', models.CharField(blank=True, max_length=100, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('battery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battery_relai_state', to='battery.battery')),
            ],
        ),
    ]
