# Generated by Django 4.2.4 on 2024-11-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battery', '0006_alter_batteryrelaistate_couleur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batteryplanning',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
