# Generated by Django 4.2.4 on 2024-11-29 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battery', '0007_batteryplanning_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batteryplanning',
            name='date_debut',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batteryplanning',
            name='date_fin',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
