# Generated by Django 4.2.4 on 2025-08-19 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battery', '0007_batteryplanning_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batteryreference',
            name='battery',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='battery_reference', to='battery.battery'),
        ),
    ]
