# Generated by Django 4.2.4 on 2025-10-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battery', '0008_alter_batteryreference_battery'),
    ]

    operations = [
        migrations.AddField(
            model_name='battery',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
