# Generated by Django 4.2.4 on 2025-12-05 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battery', '0009_battery_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batteryrelaistate',
            name='battery',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='battery_relai_state', to='battery.battery'),
        ),
    ]
