# Generated by Django 4.2.4 on 2025-08-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battery', '0009_alter_batteryreference_battery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batteryplanning',
            name='date_debut',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batteryplanning',
            name='date_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
